language: java
sudo: required
jdk:
- openjdk8
services:
- docker
script:
- "./.travis/build.sh"
branches:
  only:
  - master
env:
  global:
  - secure: atH5EI3LeqieQkLdOy8xaAgvsvgvhoBCeQdyQUWiWb2qxVx7/kiJsrQCf7mI2fkQ1Zogc+Su3J2TJ217cgBialEbTNwrQF96zjDUEjOk2O6BobrF0dhCRzYbHY0AM2wpuc/0lx6gdKHIAVxwk+1JDqxx/2OkXcpo/Ixi0isGqoa4quv4F56lECyBbM2r0GSx8wTtn0zZgQBpZXkvhU+r6si/ccTj3ve/8hqbi0beEWFbIxopGDHBvsQj3l6MuSpylpzJX6L2fhbx6GS8BQVgiUd2+PN+ry+/bGsUvleWaj/XGhSpDKuhouDwu1pi2lrLh8jMyZlHQLB5jxm9KBnoMZohXdfuyTAiTvBxE52elVVWCz4b6ZKdr/qxUlqfUzOTXB4qaCF6M1A3waIrR39iDz78uVkyHoKsS82b+uLquD3CDidZcyKASCwqqFGoxA9sm7PqD03eUop4FB/MVP2nY3al6rul0V89vrMCy1enkMdH5ozVCYbdn3mRrj14FwkYeUKcX2QsreKkgaT9ESw1+sVwOXer6VH3Xiw90XA2601B/lskUlj0p+sGQdJX1G3pj91XX2FvbdhDhaGIuCnzDwWmKlf0Tm2TAji/bLOZy+lEHjlVozE0aP1T8KTU2toFoOEZ1hNCu9SCLpORPg9LmY8pOM2poHLym+oSrczr2oc=
  - secure: lhaHsTrxXuXFBHAUEOPhqKFXPCkveeqxEZ8f/Z3lFLgXXecu60BjzhazsjU5JqDp3n/GePwtO1D06mgjjdBc6M/44Hw7ByfnKta36s0G6zSsCVGEXT/j2kgtgm+7GsDAmWDvKd8ysdW0hjpxYZ7hYriiiJUltzlBhHShnfhgCMx93wGgCWAh6KWyHYa04MfqJfNX+labGXVnHvPbAoGl0aOUhJoUZsmj2de5qmkXY9L2itxXZmfGVkBbq/O5EgMX1MN3jX9LPdscGnAg/EsvJ/CEntq7aK7mioVE0zy9o6bGZPLlMbuBbBoy7VlacsUcoT16UxVIWT/qrdHoNClTYvGHX+I7zjEiCsCncJbXzaul4XLHUZ10xziN72FKiWfwLMUaCE1fh5m9pO/X+45FGO74aylUysBO40MMtBjobVM/iPd44U6n/mDGuBei433cxi2+F2qQh+KryqeMyIIKo/yaQ+1SZeiclxAXGfeZ77IB0YRzHAk7XYU9QvdBm0eaAjy2/q2Vbp+a3IrYeZoDMz34serXHdOIOpah7aWNZjiBmqrpGmoIWsf+3N+Y9s2GqD+Lh9uxUWZRKsJeVP+DjT0JNZ6tJlGRzS08os55dTpP4IjcUHZurR+FGMNkcCixJBTh3AiYoUgmrvTVa0tEHX43SsZF5JOEekHs8YzGKG8=
